source ${HOME}/ste_bash_env

source ${HOME}/ste_java_env

. $HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh

export https_proxy=http://127.0.0.1:7890
export http_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7890

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
