source ${HOME}/ste_bash_env

source ${HOME}/ste_java_env

source /usr/local/Cellar/asdf/0.12.0/libexec/asdf.sh

export PATH="$(asdf where flutter)/bin":"$PATH"
export JAVA_HOME="$(asdf where java)"

#flutter HOME

#export FLUTTER_HOME=${HOME}/flutter
#export FLUTTER=${FUTTER_HOME}/bin

#export PATH=$FLUTTER_HOME/bin:$PATH:

export https_proxy=http://127.0.0.1:7890
export http_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7890

export PATH=${HOME}/SteTerminalConfig/bin:$PATH:
